feat: Upgrade project to circom 2
0xPARC/circom-starter pull request #6
Opened 2022-03-17 01:01 UTC by phated

This updates the hardhat-circom dependency to v3 which defaults the compiler to circom 2. This version of the plugin requires node 16+ so we've dropped support for node 14.

I've also updated the circuits to be compatible with circom 2.

2022-03-19 00:02 UTC, gubsheep requested changes
could you also replace one of the `component main = Main()` with `component main { public [ x2 ] } = Main();` to demonstrate how to mix public and private inputs?

also, suggest upgrade 2.0.0 -> 2.0.2

else lgtm! everything runs locally (including the pragma upgrade to 2.0.2)

2022-03-19 00:02 UTC, gubsheep commented on circuits/division.circom
> +pragma circom 2.0.0;
```suggestion
pragma circom 2.0.2;
```

2022-03-19 00:02 UTC, gubsheep commented on circuits/hash.circom
> +pragma circom 2.0.0;
```suggestion
pragma circom 2.0.2;
```

2022-03-19 00:02 UTC, gubsheep commented on circuits/simple-polynomial.circom
> +pragma circom 2.0.0;
```suggestion
pragma circom 2.0.2;
```

2022-03-21 00:34 UTC, phated commented
@gubsheep looks like the version of circom2 that I include has pragma 2.0.3 so I'm going to update. We'll need to get zkrepl updated to include the new version too.

2022-03-21 01:36 UTC, gubsheep approved these changes
thanks for doing this!

2022-03-21 01:38 UTC, merged